import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./header/page"; // Import the Header component
import Footer from "./footer/page"; // Import the Footer component
import AboutMe from "./about/page"; // Import the AboutMe component
import Experience from "./experience/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header /> {/* Header stays inside the body */}
        
        <main>{children}</main> {/* Main content */}

        <AboutMe /> {/* AboutMe component inside the body, below the main content */}
        <Experience/>
        <Footer /> {/* Footer component */}
      </body>
    </html>
  );
}
